### ISSUE TITLE
[Design] MainView 구현

### ISSUE THREAD

**Issue by VronzeWook** [VronzeWook/KOPIS-MaDang#11]
## 🛠 Issue

- MainView를 구현합니다.

## 📝 To-do

- [ ] Main View 구현
- [ ] What's new View 구현
- [ ] Popularity Ranking View 구현
- [ ] Genre View 구현
- [ ] Best Reviews View 구현
- [ ] Best Review cell 구현
- [ ] 데이터 연동
