### ISSUE TITLE
[Feat] Review 데이터 Main/Detail 화면 연동

### ISSUE THREAD

**Issue by VronzeWook** [VronzeWook/KOPIS-MaDang#55]
## 🛠 Issue

-  Review 데이터 Main/Detail 화면 연동
## 📝 To-do

- [ ] Review 데이터 더미 생성
- [ ] Review 데이터 Main 화면 연동!
- [ ] Review 데이터 Detail 화면 연동!
