### ISSUE TITLE
[Feat] RouterManager 구현

### ISSUE THREAD

**Issue by seoyeon-choo** [VronzeWook/KOPIS-MaDang#69]
## 📝 To-do

- [x] RouterManager 구현
- [x] 디테일 뷰 언어 설정 추가
- [x] 디테일 뷰 이미지 텍스트 추출 및 
- [x] NotificationManager 구현
- [ ] 메인 뷰 영어 제목
