### ISSUE TITLE
[Feat] 즐겨찾기 기능 구현

### ISSUE THREAD

**Issue by VronzeWook** [VronzeWook/KOPIS-MaDang#75]
## 🛠 Issue

- 즐겨찾기 버튼 기능 (Firebase 연동)
- 즐겨찾기 버튼 추가

## 📝 To-do

- [ ] 네비게이션 타이틀에 즐겨찾기 버튼 추가!
- [ ] ByGenreView에서 화면에 즐겨찾기 버튼 추가!
- [ ] 버튼 동작 시 기능 구현(Firebase 연동)
